### ISSUE TITLE
Extra spaces are not applied same way as jsbeautifier.org

### ISSUE THREAD

**Issue by PD75** [HookyQR/VSCodeBeautify#10]
From previous editors I always got a space before and after ` > ` in css.

This works on [http://jsbeautifier.org/](http://jsbeautifier.org/) :

```css
.main.row > .column.segment {
  width: 100 % ;
  flex: 1;
  overflow: auto;
  margin - bottom: 0!important;
}
```

but not with beautifier in vscode:

```css
.main.row>.column .segment {
  width: 100%;
  flex: 1;
  overflow: auto;
  margin-bottom: 0 !important;
}
```

I tried with only the ` "indent_size": 2, ` and also all default settings from js-beautify git hub instruction.
