### ISSUE TITLE
Prevent comments inside CSS rules from breaking onto a new line?

### ISSUE THREAD

**Issue by montrealist** [HookyQR/VSCodeBeautify#136]
* **Operating System (+Version)**: MacOS El Capitain v. 10.11.6
* **VS Code Version**: 1.11.2
* **beautify Version**: 1.0.2

Is there a way to **not** put CSS inline comment blocks on a new line?

.jsbeautifyrc
```javascript
{
  "indent_size": 4,
  "indent_char": " ",
  "css": {
      "space_around_combinator": true,
      "selector_separator_newline": false,
      "newline_between_rules": false
  }
}
```
## Action performed
Formatting CSS file with `HookyQR.beautifyFile` command
```css
.foobar {
    color: red; /* comment */
}
```

## Expected results
```css
.foobar {
    color: red; /* comment */
}
```

## Actual results
```css
.foobar {
    color: red;
    /* comment */
}
```

**Comment by denious** [comment]
Confirmed, cannot find an option to control this and is very annoying.

Similar weird formatting happens for:

**Expected results**
```css
.foo {
    color: red;
}

/* This comment relates to bar */
.bar {
    color: blue;
}
```

**Actual results**
```css
.foo {
    color: red;
}
/* This comment relates to bar */

.bar {
    color: blue;
}
```
