### ISSUE TITLE
newline_between_rules not working

### ISSUE THREAD

**Issue by hbj** [HookyQR/VSCodeBeautify#158]
* **Operating System (+Version)**: Mac OS X El Capitan (10.11.6)
* **VS Code Version**: 1.13.1
* **beautify Version**: 1.1.1

VS Code:
```javascript
{
  "beautify.ignore": [],
  "beautify.config": null,
  "editor.formatOnSave": true
}
```
.jsbeautifyrc
```javascript
{
  "end_with_newline": true,
  "indent_size": 2,
  "max_preserve_newlines": 2,
  "wrap_line_length": 120,
  "newline_between_rules": true,
  "space_around_combinator": true
}
```
.editorconfig
```
# editorconfig.org

root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

## Action performed
Format a scss file (on save, format document and format selection).

## Expected results
Expected formatted code to have empty lines between rules.
```scss
.main-header {
  .navbar {
    padding-left: 0;
    padding-right: 0;
  }

  > .social-icons {
    padding: 37px 0.5rem 5px 0;

    @include media-breakpoint-down(md) {
      display: none !important;
    }
  }

  .social-icons {
    a {
      display: block;
      width: 24px;
      height: 24px;
      margin-left: 0.25rem;
      margin-right: 0.25rem;
      background-repeat: no-repeat;
      background-position: center center;

      &.hubert_fb_url {
        background-image: url(../images/icon_facebook.svg);
      }

      &.hubert_twitter_url {
        background-image: url(../images/icon_twitter.svg);
      }

      &.hubert_pinterest_url {
        background-image: url(../images/icon_pinterest.svg);
      }
    }

    &.navbar-nav {
      margin-left: 0.5rem;

      a.nav-link {
        padding: 0;
        margin: $nav-link-padding;
        margin-left: 0.25rem;
        margin-right: 0.25rem;
      }
    }
  }
}
```

## Actual results
Empty lines are removed.

```scss
.main-header {
  .navbar {
    padding-left: 0;
    padding-right: 0;
  }
  > .social-icons {
    padding: 37px 0.5rem 5px 0;
    @include media-breakpoint-down(md) {
      display: none !important;
    }
  }
  .social-icons {
    a {
      display: block;
      width: 24px;
      height: 24px;
      margin-left: 0.25rem;
      margin-right: 0.25rem;
      background-repeat: no-repeat;
      background-position: center center;
      &.hubert_fb_url {
        background-image: url(../images/icon_facebook.svg);
      }
      &.hubert_twitter_url {
        background-image: url(../images/icon_twitter.svg);
      }
      &.hubert_pinterest_url {
        background-image: url(../images/icon_pinterest.svg);
      }
    }
    &.navbar-nav {
      margin-left: 0.5rem;
      a.nav-link {
        padding: 0;
        margin: $nav-link-padding;
        margin-left: 0.25rem;
        margin-right: 0.25rem;
      }
    }
  }
}
```
