### ISSUE TITLE
css (scss) comments should be on own line

### ISSUE THREAD

**Issue by Shinigami92** [HookyQR/VSCodeBeautify#166]
* **Operating System (+Version)**: Windows 10 (14393.1480)
* **VS Code Version**: 1.14.2
* **beautify Version**: 1.1.1

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
	"editor.autoIndent": true,
	"editor.cursorBlinking": "phase",
	"editor.cursorStyle": "line-thin",
	"editor.formatOnPaste": true,
	"editor.formatOnSave": true,
	"editor.formatOnType": true,
	"editor.mouseWheelZoom": true,
	"editor.multiCursorModifier": "ctrlCmd",
	"editor.renderWhitespace": "boundary",
	"editor.snippetSuggestions": "top",
	"files.eol": "\n",
	"files.insertFinalNewline": true,
	"html.format.extraLiners": "",
	"html.format.indentInnerHtml": true,
	"html.format.maxPreserveNewLines": 1,
	"javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
	"markdown.preview.markEditorSelection": false,
	"workbench.colorTheme": "Monokai Dimmed"
}
```
.jsbeautifyrc
```javascript
{
	"end_with_newline": true,
	"indent_with_tabs": true,
	"html": {
		"indent_inner_html": true,
		"max_preserve_newlines": 1,
		"extra_liners": []
	},
	"js": {
		"max_preserve_newlines": 2,
		"brace_style": "collapse,preserve-inline"
	},
	"css": {
		"space_around_combinator": true,
		"newline_between_rules": true,
		"preserve_newlines": true
	}
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command
```scss
body {
	padding-top: 70px;
	// Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes.

	// Responsive Styles
	@media (max-width: $break-large) {
		padding-top: 120px;
	}
	//
	@media (max-width: $break-small) {
		padding-top: 170px;
	}
}

// scss-lint:disable IdSelector
#container {
	// scss-lint:enable IdSelector
	td {
		&.cell-needed {
			// min-width: 120px;
			text-align: center;
			// width: 120px;
		}
	}
}
```

## Expected results
Expected ... to ...
```scss
body {
	padding-top: 70px;
	// Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes.

	// Responsive Styles
	@media (max-width: $break-large) {
		padding-top: 120px;
	}
	//
	@media (max-width: $break-small) {
		padding-top: 170px;
	}
}

// scss-lint:disable IdSelector
#container {
	// scss-lint:enable IdSelector
	td {
		&.cell-needed {
			// min-width: 120px;
			text-align: center;
			// width: 120px;
		}
	}
}
```

## Actual results
Details of what happened ...
```scss
body {
	padding-top: 70px; // Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes.
	// Responsive Styles
	@media (max-width: $break-large) {
		padding-top: 120px;
	} //
	@media (max-width: $break-small) {
		padding-top: 170px;
	}
}

// scss-lint:disable IdSelector
#container {
	// scss-lint:enable IdSelector
	td {
		&.cell-needed {
			// min-width: 120px;
			text-align: center; // width: 120px;
		}
	}
}
```
