### ISSUE TITLE
New line injected before comment in css file on each format

### ISSUE THREAD

**Issue by jwhitmarsh** [HookyQR/VSCodeBeautify#194]
* **Operating System (+Version)**: macOS 10.12.6
* **VS Code Version**: 1.18.1
* **beautify Version**: 1.1.1

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
  // List of paths to ignore when using VS Code format command, including format on save. Uses glob pattern matching.
  "beautify.ignore": [],

  // A path to file or object containing the configuration options for js-beautify. If the .jsbeautifyrc file exists in project root, it overrides this configuration.
  "beautify.config": null,

  // Link file types to the beautifier type
  "beautify.language": {
    "js": {
      "type": [
        "javascript",
        "json"
      ],
      "filename": [
        ".jshintrc",
        ".jsbeautify"
      ]
    },
    "css": [
      "css",
      "scss"
    ],
    "html": [
      "htm",
      "html"
    ]
  },
```
.jsbeautifyrc
```javascript
{
  "indent_size": 2,
  "indent_char": " ",
  "indent_level": 0,
  "indent_with_tabs": 0,
  "preserve_newlines": 1,
  "max_preserve_newlines": 2,
  "wrap_line_length": 180,
  "end_with_newline": 1,
  "space_after_anon_function": 0,
  "brace_style": "collapse-preserve-inline"
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command

## Expected results
Not inject a new line before each comment in a css file

```css 
/*
  Comment here
*/
.class{ ... }
```

## Actual results
Injects a new line before each comment in a css file

1st format
```css
              <- newline here
/*
  Comment here
*/
.class {
  display: block;
}
```

2nd format
```css
              <- newline here
              <- newline here
/*
  Comment here
*/
.class {
  display: block;
}
```
