### ISSUE TITLE
CSS Beautify adds space after comment

### ISSUE THREAD

**Issue by LunarTwilight** [HookyQR/VSCodeBeautify#208]
* **Operating System (+Version)**: Windows 10
* **VS Code Version**: 1.21.0-insiders
* **beautify Version**: 1.3.0

Settings I use: 
.jsbeautifyrc
```javascript
{
  "css": {
    "preserve_newlines": true
  }
}
```
## Action performed
Press control + shift + p and select "Beautify file"
```css
/* test */
#footer {color: pink;}
```

## Expected results
No space between comment and css
```css
/* test */
#footer {
    color: pink;
}
```

## Actual results
Space between comment and css
```css
/* test */

#footer {
    color: pink;
}
```
