### ISSUE TITLE
Comments do not keep new line format.

### ISSUE THREAD

**Issue by mago87gal** [HookyQR/VSCodeBeautify#244]
* **Windows 7 Enterprise (Service Pack 1)**: 
* **VS Code 1.23.1**: 
* **beautify Version 1.3.2**: 

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
	"editor.formatOnSave": true
}
```
.jsbeautifyrc
```javascript
{
	"preserve_newlines": true,
	"end_with_newline": true
}
```
## Action performed 
1.- save .scss file
Format javascript file with `HookyQR.beautifyFile` command
```scss
            .text {
                font-size: 17px;
                margin-top: 3px;
            }
            // The text of the buttons will be shown according to ...
            .text2 {
                font-size: 17px;
                margin-top: 3px;
            }
```
## Expected results
1.- File should look as below, with comment in a new line.
```scss
            .text {
                font-size: 17px;
                margin-top: 3px;
            }
            // The text of the buttons will be shown according to ...
            .text2 {
                font-size: 17px;
                margin-top: 3px;
            }
```
## Actual results
1.- File looks as shown below, with comment in the same line.
```scss
            .text {
                font-size: 17px;
                margin-top: 3px;
            }// The text of the buttons will be shown according to ...
            .text2 {
                font-size: 17px;
                margin-top: 3px;
            }
```
